# Generated by Django 5.2.18 on 2026-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('ready', False), models.Q(('derivative_key__isnull', False), ('height__gt', 0), ('mime', 'image/jpeg'), ('width__gt', 0), models.Q(('derivative_checksum', ''), _negated=True)), _connector='OR'), name='ready_photo_has_derivative'),
        ),
    ]
