# Generated by Django 5.2.18 on 2026-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_photo_ready_photo_has_derivative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
    ]
