# Generated by Django 5.2.18 on 2026-10-08 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geojson', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('manifest', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedMedia',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('derivative_key', models.CharField(max_length=200, unique=True)),
                ('checksum', models.CharField(max_length=64)),
                ('mime', models.CharField(max_length=40)),
                ('revoked', models.BooleanField(default=False)),
                ('retain_until', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivePublication',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.publication')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='one_active_publication')],
            },
        ),
        migrations.CreateModel(
            name='MediaGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.publication')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.publishedmedia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publication', 'media'), name='unique_publication_media')],
            },
        ),
    ]
